ISO = "bento/ubuntu-24.04"
NET = "192.168.192"
VAGRANT_SERVER_URL = 'http://vagrant.elab.pro'
DOMAIN = ".netology"
HOST_PREFIX = "server"
INVENTORY_PATH = "../ansible/inventory"

server = [
  {
    :hostname => HOST_PREFIX + "1" + DOMAIN,
    :ip => NET + "11",
    :ssh_host => "20152",
    :ssh_vm => "22",
    :ram => 1024,
    :core => 1
  } 
]
